#!/bin/sh /etc/rc.common

NAME="nsupdate.info-updater"
USE_PROCD=1
START=99

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "/usr/bin/nsupdate.info-updater"
    procd_append_param env HOST_NAME=
    procd_append_param env SECRET_KEY=
    procd_close_instance
}

service_triggers() {
    procd_add_reload_interface_trigger wan
    procd_add_reload_interface_trigger wan6
    procd_add_reload_interface_trigger br-lan
}
