#!/bin/sh /etc/rc.common

NAME="nsupdate.info-updater"
USE_PROCD=1
START=99

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "/usr/bin/nsupdate.info-updater"
    procd_append_param env HOST_NAME=
    procd_append_param env SECRET_KEY=
    procd_close_instance
}

service_triggers() {
    for interface in wan wan6 lan; do
        procd_add_interface_trigger "interface.up" $interface /etc/init.d/$NAME restart
    done
}
